server:
  port: 8080
  error:
    include-stacktrace: on_param

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

info:
  app: Spring Boot Actuator with Prometheus
  github: https://github.com/weverton-souza/java-spring-actuator-prometheus
